### ISSUE TITLE
Кое не правя Както трябва с контейнеризацията?

### ISSUE THREAD

**Issue by borisboev79** [luchob/softuni-feb2023#109]
Здрасти, Лъчо,

за пореден път не се преборвам с проблем, който правя по твоите стъпки, но не разбирам съвсем грешката ми къде е.

На първо място изобщо правилно ли е да сменям стойността на  MYSQL_ALLOW_EMPTY_PASSWORD="no" на "yes"

аз я промених, защото така работи моята база и имам зададена парола в променливите. После си мислех да не би да е заради факта, че sql сървърът на компютъра си ми работи, но нали докер си рънва собствени инстанции на включените в имиджа депендънсита?

Ето линк към докер имиджа ми, не знам дали като пише, че е публичен, ти ще го видиш, защото ми е още ново това:
https://hub.docker.com/repository/docker/boboev/cgm

Ако не става, ето ми и репото:
https://github.com/borisboev79/CGM-Project.git

Пак благодаря предварително. Не знам дали получаваш известия за коментари, които съм ти пискал във вече затворени issues, но ако не - още веднъж да кажа, че намирам тези твои включвания тук на моменти за по-стойностни от целия модул.

Поздрави,
Боби

**Comment by luchob** [comment]
Здрасти! 

Ами като пусна композицията ти виждам това нещо:

```
deployment-cgm-0.8.0-1  | java.sql.SQLException: Access denied for user 'root'@'172.19.0.4' (using password: YES)
``` 

Значи - so far so good. Опитваш се да се свържеш с user root с някаква парола 1234, но къде си казал на MySQL image-a че това му е паролата за руут usera? Май никъде :-) Значи не е настроено както трябва. Може алтернативно да създадеш друг юзър, ето така:

```
  db:
    image: arm64v8/mysql:oracle
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="no"
      - MYSQL_DATABASE=cruisegroups
      - MYSQL_USER=cg
      - MYSQL_PASSWORD=1234
```
Т.е. вече ако имаш user cg с парола 1234. Ето какво пише в[ документацията на имиджа](https://hub.docker.com/r/arm64v8/mysql/):

**MYSQL_USER, MYSQL_PASSWORD**
_These variables are optional, used in conjunction to create a new user and to set that user's password. This user will be granted superuser permissions (see above) for the database specified by the MYSQL_DATABASE variable. Both variables are required for a user to be created.

Do note that there is no need to use this mechanism to create the root superuser, that user gets created by default with the password specified by the MYSQL_ROOT_PASSWORD variable._

Супер, сега ти остава да настроиш и собствения си имидж:

```
  cgm-0.8.0:
    image: boboev/cgm:v0.8
    depends_on: [db]
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=cg
      - MYSQL_PASSWORD=1234
```

И хоп, вече и твоя имидж има и юзер/парола. Пускаш го и той се връзва с ДБ и лъсва следващия проблем:

```
 Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'MAIL_PASSWORD' in value "${MAIL_PASSWORD}"
```

Ако си стигнал до тук и четеш тези редове, мисля че може да се оправиш с този проблем вече :-) :-) 

**МНОГО Важна забележка!!!**

**arm64v8/mysql:oracle** е имидж за MAC с M1 чип! Ако си с друга машина няма да работи! В такъв случай трябва да подбереш имиджа за твоята архитектура.

Поздрави,
Л.
