### ISSUE TITLE
Cloudinary in docker-compose - How?

### ISSUE THREAD

**Issue by Maria-Pavlova** [luchob/softuni-feb2023#128]
Здравей, след справяне с всевъзможни db connection грешки стигнах до следните: db - върви, но app deployment-a гърми с това:
- Error creating bean with name 'cloudinaryConfig': Injection of autowired dependencies failed
- Could not resolve placeholder 'CLOUDINARY_API_SECRET' in value "${CLOUDINARY_API_SECRET}"
 Ясно ми е, че трябва да го сетна в docker-compose, но не знам как. 
https://github.com/Maria-Pavlova/HomeExchange_SimpleVersion

Поздрави,
Мария

**Comment by luchob** [comment]
Здрасти! Как не знаеш, като вече го правиш с креденшълите на базата :-) Същото е:

```
  HomeExchange_SimpleVersion:
    image: mimip/home_exchange:v1
    depends_on: [db]
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=he
      - MYSQL_PASSWORD=workbench
      - HOSTNAME=http://localhost:8080
      - CLOUDINARY_API_SECRET= <---------- 🤓 
```

Поздрави от гората :-)
